all: a b c d

a: a.cpp
	g++ -std=c++14 a.cpp -o a.out

b: b.cpp
	g++ -std=c++14 b.cpp -o b.out

c: c.cpp
	g++ -std=c++14 c.cpp -o c.out

d: d.cpp
	g++ -std=c++14 d.cpp -o d.out

clean:
	rm -rf a.out b.out c.out d.out

